/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherTestsRouteImport } from './routes/teacher.tests'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherNewRouteImport } from './routes/teacher.new'
import { Route as TeacherFeesRouteImport } from './routes/teacher.fees'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as StudentAiRouteImport } from './routes/student.ai'
import { Route as ReportCodeRouteImport } from './routes/report.$code'
import { Route as TeacherTestsIdRouteImport } from './routes/teacher.tests.$id'
import { Route as StudentTestIdRouteImport } from './routes/student.test.$id'
import { Route as ApiPublicSarvamTtsRouteImport } from './routes/api/public/sarvam-tts'
import { Route as ApiPublicSarvamSttRouteImport } from './routes/api/public/sarvam-stt'
import { Route as ApiPublicGenerateQuestionsRouteImport } from './routes/api/public/generate-questions'
import { Route as ApiPublicAiStudyChatRouteImport } from './routes/api/public/ai-study-chat'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestsRoute = TeacherTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNewRoute = TeacherNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFeesRoute = TeacherFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentAiRoute = StudentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => StudentRoute,
} as any)
const ReportCodeRoute = ReportCodeRouteImport.update({
  id: '/report/$code',
  path: '/report/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTestsIdRoute = TeacherTestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherTestsRoute,
} as any)
const StudentTestIdRoute = StudentTestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => StudentRoute,
} as any)
const ApiPublicSarvamTtsRoute = ApiPublicSarvamTtsRouteImport.update({
  id: '/api/public/sarvam-tts',
  path: '/api/public/sarvam-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSarvamSttRoute = ApiPublicSarvamSttRouteImport.update({
  id: '/api/public/sarvam-stt',
  path: '/api/public/sarvam-stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateQuestionsRoute =
  ApiPublicGenerateQuestionsRouteImport.update({
    id: '/api/public/generate-questions',
    path: '/api/public/generate-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiStudyChatRoute = ApiPublicAiStudyChatRouteImport.update({
  id: '/api/public/ai-study-chat',
  path: '/api/public/ai-study-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/report/$code': typeof ReportCodeRoute
  '/student/ai': typeof StudentAiRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/new': typeof TeacherNewRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/tests': typeof TeacherTestsRouteWithChildren
  '/teacher/': typeof TeacherIndexRoute
  '/api/public/ai-study-chat': typeof ApiPublicAiStudyChatRoute
  '/api/public/generate-questions': typeof ApiPublicGenerateQuestionsRoute
  '/api/public/sarvam-stt': typeof ApiPublicSarvamSttRoute
  '/api/public/sarvam-tts': typeof ApiPublicSarvamTtsRoute
  '/student/test/$id': typeof StudentTestIdRoute
  '/teacher/tests/$id': typeof TeacherTestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/report/$code': typeof ReportCodeRoute
  '/student/ai': typeof StudentAiRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/new': typeof TeacherNewRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/tests': typeof TeacherTestsRouteWithChildren
  '/teacher': typeof TeacherIndexRoute
  '/api/public/ai-study-chat': typeof ApiPublicAiStudyChatRoute
  '/api/public/generate-questions': typeof ApiPublicGenerateQuestionsRoute
  '/api/public/sarvam-stt': typeof ApiPublicSarvamSttRoute
  '/api/public/sarvam-tts': typeof ApiPublicSarvamTtsRoute
  '/student/test/$id': typeof StudentTestIdRoute
  '/teacher/tests/$id': typeof TeacherTestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/report/$code': typeof ReportCodeRoute
  '/student/ai': typeof StudentAiRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/new': typeof TeacherNewRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/tests': typeof TeacherTestsRouteWithChildren
  '/teacher/': typeof TeacherIndexRoute
  '/api/public/ai-study-chat': typeof ApiPublicAiStudyChatRoute
  '/api/public/generate-questions': typeof ApiPublicGenerateQuestionsRoute
  '/api/public/sarvam-stt': typeof ApiPublicSarvamSttRoute
  '/api/public/sarvam-tts': typeof ApiPublicSarvamTtsRoute
  '/student/test/$id': typeof StudentTestIdRoute
  '/teacher/tests/$id': typeof TeacherTestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/teacher'
    | '/report/$code'
    | '/student/ai'
    | '/teacher/dashboard'
    | '/teacher/fees'
    | '/teacher/new'
    | '/teacher/reports'
    | '/teacher/students'
    | '/teacher/tests'
    | '/teacher/'
    | '/api/public/ai-study-chat'
    | '/api/public/generate-questions'
    | '/api/public/sarvam-stt'
    | '/api/public/sarvam-tts'
    | '/student/test/$id'
    | '/teacher/tests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/report/$code'
    | '/student/ai'
    | '/teacher/dashboard'
    | '/teacher/fees'
    | '/teacher/new'
    | '/teacher/reports'
    | '/teacher/students'
    | '/teacher/tests'
    | '/teacher'
    | '/api/public/ai-study-chat'
    | '/api/public/generate-questions'
    | '/api/public/sarvam-stt'
    | '/api/public/sarvam-tts'
    | '/student/test/$id'
    | '/teacher/tests/$id'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/teacher'
    | '/report/$code'
    | '/student/ai'
    | '/teacher/dashboard'
    | '/teacher/fees'
    | '/teacher/new'
    | '/teacher/reports'
    | '/teacher/students'
    | '/teacher/tests'
    | '/teacher/'
    | '/api/public/ai-study-chat'
    | '/api/public/generate-questions'
    | '/api/public/sarvam-stt'
    | '/api/public/sarvam-tts'
    | '/student/test/$id'
    | '/teacher/tests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  ReportCodeRoute: typeof ReportCodeRoute
  ApiPublicAiStudyChatRoute: typeof ApiPublicAiStudyChatRoute
  ApiPublicGenerateQuestionsRoute: typeof ApiPublicGenerateQuestionsRoute
  ApiPublicSarvamSttRoute: typeof ApiPublicSarvamSttRoute
  ApiPublicSarvamTtsRoute: typeof ApiPublicSarvamTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/tests': {
      id: '/teacher/tests'
      path: '/tests'
      fullPath: '/teacher/tests'
      preLoaderRoute: typeof TeacherTestsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/new': {
      id: '/teacher/new'
      path: '/new'
      fullPath: '/teacher/new'
      preLoaderRoute: typeof TeacherNewRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/fees': {
      id: '/teacher/fees'
      path: '/fees'
      fullPath: '/teacher/fees'
      preLoaderRoute: typeof TeacherFeesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/ai': {
      id: '/student/ai'
      path: '/ai'
      fullPath: '/student/ai'
      preLoaderRoute: typeof StudentAiRouteImport
      parentRoute: typeof StudentRoute
    }
    '/report/$code': {
      id: '/report/$code'
      path: '/report/$code'
      fullPath: '/report/$code'
      preLoaderRoute: typeof ReportCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/tests/$id': {
      id: '/teacher/tests/$id'
      path: '/$id'
      fullPath: '/teacher/tests/$id'
      preLoaderRoute: typeof TeacherTestsIdRouteImport
      parentRoute: typeof TeacherTestsRoute
    }
    '/student/test/$id': {
      id: '/student/test/$id'
      path: '/test/$id'
      fullPath: '/student/test/$id'
      preLoaderRoute: typeof StudentTestIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/public/sarvam-tts': {
      id: '/api/public/sarvam-tts'
      path: '/api/public/sarvam-tts'
      fullPath: '/api/public/sarvam-tts'
      preLoaderRoute: typeof ApiPublicSarvamTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sarvam-stt': {
      id: '/api/public/sarvam-stt'
      path: '/api/public/sarvam-stt'
      fullPath: '/api/public/sarvam-stt'
      preLoaderRoute: typeof ApiPublicSarvamSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-questions': {
      id: '/api/public/generate-questions'
      path: '/api/public/generate-questions'
      fullPath: '/api/public/generate-questions'
      preLoaderRoute: typeof ApiPublicGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-study-chat': {
      id: '/api/public/ai-study-chat'
      path: '/api/public/ai-study-chat'
      fullPath: '/api/public/ai-study-chat'
      preLoaderRoute: typeof ApiPublicAiStudyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentRouteChildren {
  StudentAiRoute: typeof StudentAiRoute
  StudentTestIdRoute: typeof StudentTestIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiRoute: StudentAiRoute,
  StudentTestIdRoute: StudentTestIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherTestsRouteChildren {
  TeacherTestsIdRoute: typeof TeacherTestsIdRoute
}

const TeacherTestsRouteChildren: TeacherTestsRouteChildren = {
  TeacherTestsIdRoute: TeacherTestsIdRoute,
}

const TeacherTestsRouteWithChildren = TeacherTestsRoute._addFileChildren(
  TeacherTestsRouteChildren,
)

interface TeacherRouteChildren {
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherFeesRoute: typeof TeacherFeesRoute
  TeacherNewRoute: typeof TeacherNewRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherTestsRoute: typeof TeacherTestsRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherFeesRoute: TeacherFeesRoute,
  TeacherNewRoute: TeacherNewRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherTestsRoute: TeacherTestsRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  ReportCodeRoute: ReportCodeRoute,
  ApiPublicAiStudyChatRoute: ApiPublicAiStudyChatRoute,
  ApiPublicGenerateQuestionsRoute: ApiPublicGenerateQuestionsRoute,
  ApiPublicSarvamSttRoute: ApiPublicSarvamSttRoute,
  ApiPublicSarvamTtsRoute: ApiPublicSarvamTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
