ALTER TABLE public.site_themes
  ADD COLUMN IF NOT EXISTS css text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS js text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS target text NOT NULL DEFAULT 'global';